/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anchors</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.canvas.language.canvas.Anchors#getStartAnchor <em>Start Anchor</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Anchors#getEndAnchor <em>End Anchor</em>}</li>
 * </ul>
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getAnchors()
 * @model
 * @generated
 */
public interface Anchors extends EObject
{
  /**
   * Returns the value of the '<em><b>Start Anchor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Anchor</em>' containment reference.
   * @see #setStartAnchor(StartAnchor)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getAnchors_StartAnchor()
   * @model containment="true"
   * @generated
   */
  StartAnchor getStartAnchor();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Anchors#getStartAnchor <em>Start Anchor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Anchor</em>' containment reference.
   * @see #getStartAnchor()
   * @generated
   */
  void setStartAnchor(StartAnchor value);

  /**
   * Returns the value of the '<em><b>End Anchor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Anchor</em>' containment reference.
   * @see #setEndAnchor(EndAnchor)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getAnchors_EndAnchor()
   * @model containment="true"
   * @generated
   */
  EndAnchor getEndAnchor();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Anchors#getEndAnchor <em>End Anchor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Anchor</em>' containment reference.
   * @see #getEndAnchor()
   * @generated
   */
  void setEndAnchor(EndAnchor value);

} // Anchors
