/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bounds</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.canvas.language.canvas.Bounds#getX <em>X</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Bounds#getY <em>Y</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Bounds#getW <em>W</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Bounds#getH <em>H</em>}</li>
 * </ul>
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getBounds()
 * @model
 * @generated
 */
public interface Bounds extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getBounds_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Bounds#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getBounds_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Bounds#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>W</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>W</em>' attribute.
   * @see #setW(int)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getBounds_W()
   * @model
   * @generated
   */
  int getW();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Bounds#getW <em>W</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>W</em>' attribute.
   * @see #getW()
   * @generated
   */
  void setW(int value);

  /**
   * Returns the value of the '<em><b>H</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>H</em>' attribute.
   * @see #setH(int)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getBounds_H()
   * @model
   * @generated
   */
  int getH();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Bounds#getH <em>H</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>H</em>' attribute.
   * @see #getH()
   * @generated
   */
  void setH(int value);

} // Bounds
