/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends EObject
{
} // Container
