/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floating Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.canvas.language.canvas.FloatingText#getRect <em>Rect</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.FloatingText#getAssociated <em>Associated</em>}</li>
 * </ul>
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText()
 * @model
 * @generated
 */
public interface FloatingText extends EObject
{
  /**
   * Returns the value of the '<em><b>Rect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rect</em>' containment reference.
   * @see #setRect(Rectangle)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText_Rect()
   * @model containment="true"
   * @generated
   */
  Rectangle getRect();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.FloatingText#getRect <em>Rect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rect</em>' containment reference.
   * @see #getRect()
   * @generated
   */
  void setRect(Rectangle value);

  /**
   * Returns the value of the '<em><b>Associated</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Associated</em>' containment reference.
   * @see #setAssociated(EObject)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText_Associated()
   * @model containment="true"
   * @generated
   */
  EObject getAssociated();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.FloatingText#getAssociated <em>Associated</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Associated</em>' containment reference.
   * @see #getAssociated()
   * @generated
   */
  void setAssociated(EObject value);

} // FloatingText
