/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floating Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.canvas.language.canvas.FloatingText#getBounds <em>Bounds</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.FloatingText#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText()
 * @model
 * @generated
 */
public interface FloatingText extends EObject
{
  /**
   * Returns the value of the '<em><b>Bounds</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bounds</em>' containment reference.
   * @see #setBounds(Bounds)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText_Bounds()
   * @model containment="true"
   * @generated
   */
  Bounds getBounds();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.FloatingText#getBounds <em>Bounds</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bounds</em>' containment reference.
   * @see #getBounds()
   * @generated
   */
  void setBounds(Bounds value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(EnumEnd)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getFloatingText_End()
   * @model containment="true"
   * @generated
   */
  EnumEnd getEnd();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.FloatingText#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(EnumEnd value);

} // FloatingText
