/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape Container</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShapeContainer()
 * @model
 * @generated
 */
public interface ShapeContainer extends Container
{
} // ShapeContainer
