/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shape</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtuml.canvas.language.canvas.Shape#getName <em>Name</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Shape#getProps <em>Props</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Shape#getRect <em>Rect</em>}</li>
 *   <li>{@link org.xtuml.canvas.language.canvas.Shape#getRepresents <em>Represents</em>}</li>
 * </ul>
 *
 * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShape()
 * @model
 * @generated
 */
public interface Shape extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShape_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Shape#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Props</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Props</em>' containment reference.
   * @see #setProps(ShapeProps)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShape_Props()
   * @model containment="true"
   * @generated
   */
  ShapeProps getProps();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Shape#getProps <em>Props</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Props</em>' containment reference.
   * @see #getProps()
   * @generated
   */
  void setProps(ShapeProps value);

  /**
   * Returns the value of the '<em><b>Rect</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rect</em>' containment reference.
   * @see #setRect(Rectangle)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShape_Rect()
   * @model containment="true"
   * @generated
   */
  Rectangle getRect();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Shape#getRect <em>Rect</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rect</em>' containment reference.
   * @see #getRect()
   * @generated
   */
  void setRect(Rectangle value);

  /**
   * Returns the value of the '<em><b>Represents</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Represents</em>' attribute.
   * @see #setRepresents(String)
   * @see org.xtuml.canvas.language.canvas.CanvasPackage#getShape_Represents()
   * @model
   * @generated
   */
  String getRepresents();

  /**
   * Sets the value of the '{@link org.xtuml.canvas.language.canvas.Shape#getRepresents <em>Represents</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Represents</em>' attribute.
   * @see #getRepresents()
   * @generated
   */
  void setRepresents(String value);

} // Shape
