/*
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtuml.canvas.language.services.CanvasGrammarAccess;

@SuppressWarnings("all")
public class CanvasSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CanvasGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Anchors_AnchorsKeyword_0_1_or___AnchorsKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_ConnectorAnchorElement_SegmentAnchorKeyword_0_1_or___SegmentAnchorKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_ConnectorProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Connector_ConnectorKeyword_0_1_or___ConnectorKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_Connector_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__;
	protected AbstractElementAlias match_Connectors_ConnectorsKeyword_1_1_or___ConnectorsKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Container_FalseKeyword_2_1_or_TrueKeyword_2_0;
	protected AbstractElementAlias match_EndAnchor_EndKeyword_0_1_or___EndKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_FloatingText_TextKeyword_1_1_or___TextKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_FloatingTexts_TextsKeyword_1_1_or___TextsKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_ModelProperties_PropertiesKeyword_0_1_or___PropertiesKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_ModelProperties_ViewportKeyword_1_1_or___ViewportKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Model_RenderKeyword_1_1_or___RenderKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Polyline_PolylineKeyword_1_1_or___PolylineKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Rectangle_RectangleKeyword_0_1_or___RectangleKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_Segment_SegmentKeyword_0_1_or___SegmentKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_ShapeAnchorElement_ShapeAnchorKeyword_0_1_or___ShapeAnchorKeyword_0_0_0_ColonKeyword_0_0_1__;
	protected AbstractElementAlias match_ShapeProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Shape_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__;
	protected AbstractElementAlias match_Shape_ShapeKeyword_1_1_or___ShapeKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_Shapes_ShapesKeyword_1_1_or___ShapesKeyword_1_0_0_ColonKeyword_1_0_1__;
	protected AbstractElementAlias match_StartAnchor_StartKeyword_0_1_or___StartKeyword_0_0_0_ColonKeyword_0_0_1__;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CanvasGrammarAccess) access;
		match_Anchors_AnchorsKeyword_0_1_or___AnchorsKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getAnchorsAccess().getAnchorsKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getAnchorsAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getAnchorsAccess().getAnchorsKeyword_0_1()));
		match_ConnectorAnchorElement_SegmentAnchorKeyword_0_1_or___SegmentAnchorKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getConnectorAnchorElementAccess().getSegmentAnchorKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getConnectorAnchorElementAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getConnectorAnchorElementAccess().getSegmentAnchorKeyword_0_1()));
		match_ConnectorProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getConnectorPropsAccess().getPropertiesKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getConnectorPropsAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getConnectorPropsAccess().getPropertiesKeyword_1_1()));
		match_Connector_ConnectorKeyword_0_1_or___ConnectorKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getConnectorAccess().getConnectorKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getConnectorAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getConnectorAccess().getConnectorKeyword_0_1()));
		match_Connector_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getConnectorAccess().getRenderKeyword_5_0_0()), new TokenAlias(false, false, grammarAccess.getConnectorAccess().getColonKeyword_5_0_1())), new TokenAlias(false, false, grammarAccess.getConnectorAccess().getRenderKeyword_5_1()));
		match_Connectors_ConnectorsKeyword_1_1_or___ConnectorsKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getConnectorsAccess().getConnectorsKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getConnectorsAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getConnectorsAccess().getConnectorsKeyword_1_1()));
		match_Container_FalseKeyword_2_1_or_TrueKeyword_2_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getContainerAccess().getFalseKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getContainerAccess().getTrueKeyword_2_0()));
		match_EndAnchor_EndKeyword_0_1_or___EndKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getEndAnchorAccess().getEndKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getEndAnchorAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getEndAnchorAccess().getEndKeyword_0_1()));
		match_FloatingText_TextKeyword_1_1_or___TextKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getFloatingTextAccess().getTextKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getFloatingTextAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getFloatingTextAccess().getTextKeyword_1_1()));
		match_FloatingTexts_TextsKeyword_1_1_or___TextsKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getFloatingTextsAccess().getTextsKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getFloatingTextsAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getFloatingTextsAccess().getTextsKeyword_1_1()));
		match_ModelProperties_PropertiesKeyword_0_1_or___PropertiesKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getPropertiesKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getPropertiesKeyword_0_1()));
		match_ModelProperties_ViewportKeyword_1_1_or___ViewportKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getViewportKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getModelPropertiesAccess().getViewportKeyword_1_1()));
		match_Model_RenderKeyword_1_1_or___RenderKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getModelAccess().getRenderKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getModelAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getModelAccess().getRenderKeyword_1_1()));
		match_Polyline_PolylineKeyword_1_1_or___PolylineKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getPolylineAccess().getPolylineKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getPolylineAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getPolylineAccess().getPolylineKeyword_1_1()));
		match_Rectangle_RectangleKeyword_0_1_or___RectangleKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getRectangleAccess().getRectangleKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getRectangleAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getRectangleAccess().getRectangleKeyword_0_1()));
		match_Segment_SegmentKeyword_0_1_or___SegmentKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getSegmentAccess().getSegmentKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getSegmentAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getSegmentAccess().getSegmentKeyword_0_1()));
		match_ShapeAnchorElement_ShapeAnchorKeyword_0_1_or___ShapeAnchorKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getShapeAnchorElementAccess().getShapeAnchorKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getShapeAnchorElementAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getShapeAnchorElementAccess().getShapeAnchorKeyword_0_1()));
		match_ShapeProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getShapePropsAccess().getPropertiesKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getShapePropsAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getShapePropsAccess().getPropertiesKeyword_1_1()));
		match_Shape_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getShapeAccess().getRenderKeyword_5_0_0()), new TokenAlias(false, false, grammarAccess.getShapeAccess().getColonKeyword_5_0_1())), new TokenAlias(false, false, grammarAccess.getShapeAccess().getRenderKeyword_5_1()));
		match_Shape_ShapeKeyword_1_1_or___ShapeKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getShapeAccess().getShapeKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getShapeAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getShapeAccess().getShapeKeyword_1_1()));
		match_Shapes_ShapesKeyword_1_1_or___ShapesKeyword_1_0_0_ColonKeyword_1_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getShapesAccess().getShapesKeyword_1_0_0()), new TokenAlias(false, false, grammarAccess.getShapesAccess().getColonKeyword_1_0_1())), new TokenAlias(false, false, grammarAccess.getShapesAccess().getShapesKeyword_1_1()));
		match_StartAnchor_StartKeyword_0_1_or___StartKeyword_0_0_0_ColonKeyword_0_0_1__ = new AlternativeAlias(false, false, new GroupAlias(false, false, new TokenAlias(false, false, grammarAccess.getStartAnchorAccess().getStartKeyword_0_0_0()), new TokenAlias(false, false, grammarAccess.getStartAnchorAccess().getColonKeyword_0_0_1())), new TokenAlias(false, false, grammarAccess.getStartAnchorAccess().getStartKeyword_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Anchors_AnchorsKeyword_0_1_or___AnchorsKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_Anchors_AnchorsKeyword_0_1_or___AnchorsKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ConnectorAnchorElement_SegmentAnchorKeyword_0_1_or___SegmentAnchorKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_ConnectorAnchorElement_SegmentAnchorKeyword_0_1_or___SegmentAnchorKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ConnectorProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_ConnectorProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Connector_ConnectorKeyword_0_1_or___ConnectorKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_Connector_ConnectorKeyword_0_1_or___ConnectorKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Connector_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__.equals(syntax))
				emit_Connector_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Connectors_ConnectorsKeyword_1_1_or___ConnectorsKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_Connectors_ConnectorsKeyword_1_1_or___ConnectorsKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Container_FalseKeyword_2_1_or_TrueKeyword_2_0.equals(syntax))
				emit_Container_FalseKeyword_2_1_or_TrueKeyword_2_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EndAnchor_EndKeyword_0_1_or___EndKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_EndAnchor_EndKeyword_0_1_or___EndKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FloatingText_TextKeyword_1_1_or___TextKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_FloatingText_TextKeyword_1_1_or___TextKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FloatingTexts_TextsKeyword_1_1_or___TextsKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_FloatingTexts_TextsKeyword_1_1_or___TextsKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ModelProperties_PropertiesKeyword_0_1_or___PropertiesKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_ModelProperties_PropertiesKeyword_0_1_or___PropertiesKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ModelProperties_ViewportKeyword_1_1_or___ViewportKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_ModelProperties_ViewportKeyword_1_1_or___ViewportKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Model_RenderKeyword_1_1_or___RenderKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_Model_RenderKeyword_1_1_or___RenderKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Polyline_PolylineKeyword_1_1_or___PolylineKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_Polyline_PolylineKeyword_1_1_or___PolylineKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rectangle_RectangleKeyword_0_1_or___RectangleKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_Rectangle_RectangleKeyword_0_1_or___RectangleKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Segment_SegmentKeyword_0_1_or___SegmentKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_Segment_SegmentKeyword_0_1_or___SegmentKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ShapeAnchorElement_ShapeAnchorKeyword_0_1_or___ShapeAnchorKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_ShapeAnchorElement_ShapeAnchorKeyword_0_1_or___ShapeAnchorKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ShapeProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_ShapeProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Shape_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__.equals(syntax))
				emit_Shape_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Shape_ShapeKeyword_1_1_or___ShapeKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_Shape_ShapeKeyword_1_1_or___ShapeKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Shapes_ShapesKeyword_1_1_or___ShapesKeyword_1_0_0_ColonKeyword_1_0_1__.equals(syntax))
				emit_Shapes_ShapesKeyword_1_1_or___ShapesKeyword_1_0_0_ColonKeyword_1_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StartAnchor_StartKeyword_0_1_or___StartKeyword_0_0_0_ColonKeyword_0_0_1__.equals(syntax))
				emit_StartAnchor_StartKeyword_0_1_or___StartKeyword_0_0_0_ColonKeyword_0_0_1__(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('anchors' ':') | 'anchors:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) startAnchor=StartAnchor
	 */
	protected void emit_Anchors_AnchorsKeyword_0_1_or___AnchorsKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('segmentAnchor' ':') | 'segmentAnchor:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) element=[Connector|ID]
	 */
	protected void emit_ConnectorAnchorElement_SegmentAnchorKeyword_0_1_or___SegmentAnchorKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('properties' ':') | 'properties:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) color=Color
	 */
	protected void emit_ConnectorProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('connector' ':') | 'connector:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_Connector_ConnectorKeyword_0_1_or___ConnectorKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('render' ':') | 'render:'
	 *
	 * This ambiguous syntax occurs at:
	 *     anchors=Anchors (ambiguity) represents=STRING
	 *     name=ID (ambiguity) represents=STRING
	 *     polyline=Polyline (ambiguity) represents=STRING
	 *     props=ConnectorProps (ambiguity) represents=STRING
	 */
	protected void emit_Connector_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('connectors' ':') | 'connectors:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) connectors+=Connector
	 */
	protected void emit_Connectors_ConnectorsKeyword_1_1_or___ConnectorsKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'true' | 'false'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'container' (ambiguity) (rule start)
	 */
	protected void emit_Container_FalseKeyword_2_1_or_TrueKeyword_2_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('end' ':') | 'end'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) point=Point
	 */
	protected void emit_EndAnchor_EndKeyword_0_1_or___EndKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('text' ':') | 'text:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) rect=Rectangle
	 */
	protected void emit_FloatingText_TextKeyword_1_1_or___TextKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('texts' ':') | 'texts:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) texts+=FloatingText
	 */
	protected void emit_FloatingTexts_TextsKeyword_1_1_or___TextsKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('properties' ':') | 'properties:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (('viewport' ':') | 'viewport:') point=Point
	 */
	protected void emit_ModelProperties_PropertiesKeyword_0_1_or___PropertiesKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('viewport' ':') | 'viewport:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (('properties' ':') | 'properties:') (ambiguity) point=Point
	 */
	protected void emit_ModelProperties_ViewportKeyword_1_1_or___ViewportKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('render' ':') | 'render:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) represents=STRING
	 *     semantics+=SemanticModel (ambiguity) represents=STRING
	 */
	protected void emit_Model_RenderKeyword_1_1_or___RenderKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('polyline' ':') | 'polyline:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) segments+=Segment
	 */
	protected void emit_Polyline_PolylineKeyword_1_1_or___PolylineKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('rectangle' ':') | 'rectangle:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'x' x=INT
	 */
	protected void emit_Rectangle_RectangleKeyword_0_1_or___RectangleKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('segment' ':') | 'segment:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) startPoint=Point
	 */
	protected void emit_Segment_SegmentKeyword_0_1_or___SegmentKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('shapeAnchor' ':') | 'shapeAnchor:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) element=[Shape|ID]
	 */
	protected void emit_ShapeAnchorElement_ShapeAnchorKeyword_0_1_or___ShapeAnchorKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('properties' ':') | 'properties:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) color=Color
	 *     (rule start) (ambiguity) container=Container
	 */
	protected void emit_ShapeProps_PropertiesKeyword_1_1_or___PropertiesKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('render' ':') | 'render:'
	 *
	 * This ambiguous syntax occurs at:
	 *     rect=Rectangle (ambiguity) represents=STRING
	 */
	protected void emit_Shape_RenderKeyword_5_1_or___RenderKeyword_5_0_0_ColonKeyword_5_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('shape' ':') | 'shape:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) name=ID
	 */
	protected void emit_Shape_ShapeKeyword_1_1_or___ShapeKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('shapes' ':') | 'shapes:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     (rule start) (ambiguity) shapes+=Shape
	 */
	protected void emit_Shapes_ShapesKeyword_1_1_or___ShapesKeyword_1_0_0_ColonKeyword_1_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('start' ':') | 'start:'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) point=Point
	 */
	protected void emit_StartAnchor_StartKeyword_0_1_or___StartKeyword_0_0_0_ColonKeyword_0_0_1__(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
