/*
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtuml.canvas.language.ui.internal.LanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CanvasExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LanguageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LanguageActivator activator = LanguageActivator.getInstance();
		return activator != null ? activator.getInjector(LanguageActivator.ORG_XTUML_CANVAS_LANGUAGE_CANVAS) : null;
	}

}
