/*
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtuml.canvas.language.parser.antlr.internal.InternalCanvasParser;
import org.xtuml.canvas.language.services.CanvasGrammarAccess;

public class CanvasParser extends AbstractAntlrParser {

	@Inject
	private CanvasGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCanvasParser createParser(XtextTokenStream stream) {
		return new InternalCanvasParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CanvasGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CanvasGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
