/**
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.canvas.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtuml.canvas.language.canvas.CanvasPackage;
import org.xtuml.canvas.language.canvas.ShapeContainer;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shape Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ShapeContainerImpl extends ContainerImpl implements ShapeContainer
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShapeContainerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CanvasPackage.Literals.SHAPE_CONTAINER;
  }

} //ShapeContainerImpl
