/*
 * generated by Xtext 2.22.0
 */
package org.xtuml.canvas.language.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CanvasGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRenderAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cRenderModelRenderParserRuleCall_0_0 = (RuleCall)cRenderAssignment_0.eContents().get(0);
		private final Assignment cPropertiesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPropertiesModelPropertiesParserRuleCall_1_0 = (RuleCall)cPropertiesAssignment_1.eContents().get(0);
		private final Assignment cElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cElementsGraphicalElementParserRuleCall_2_0 = (RuleCall)cElementsAssignment_2.eContents().get(0);
		
		//Model:
		//	render=ModelRender
		//	properties=ModelProperties?
		//	elements+=GraphicalElement*;
		@Override public ParserRule getRule() { return rule; }
		
		//render=ModelRender properties=ModelProperties? elements+=GraphicalElement*
		public Group getGroup() { return cGroup; }
		
		//render=ModelRender
		public Assignment getRenderAssignment_0() { return cRenderAssignment_0; }
		
		//ModelRender
		public RuleCall getRenderModelRenderParserRuleCall_0_0() { return cRenderModelRenderParserRuleCall_0_0; }
		
		//properties=ModelProperties?
		public Assignment getPropertiesAssignment_1() { return cPropertiesAssignment_1; }
		
		//ModelProperties
		public RuleCall getPropertiesModelPropertiesParserRuleCall_1_0() { return cPropertiesModelPropertiesParserRuleCall_1_0; }
		
		//elements+=GraphicalElement*
		public Assignment getElementsAssignment_2() { return cElementsAssignment_2; }
		
		//GraphicalElement
		public RuleCall getElementsGraphicalElementParserRuleCall_2_0() { return cElementsGraphicalElementParserRuleCall_2_0; }
	}
	public class ModelRenderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.ModelRender");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cRenderKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cRenderKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		//ModelRender:
		//	('render' ':' | 'render:') importURI=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//('render' ':' | 'render:') importURI=STRING
		public Group getGroup() { return cGroup; }
		
		//('render' ':' | 'render:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'render' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'render'
		public Keyword getRenderKeyword_0_0_0() { return cRenderKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'render:'
		public Keyword getRenderKeyword_0_1() { return cRenderKeyword_0_1; }
		
		//importURI=STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }
		
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}
	public class ModelPropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.ModelProperties");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cPropertiesKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cPropertiesKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cViewportKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cViewportKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cPointAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPointPointParserRuleCall_2_0 = (RuleCall)cPointAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cZoomKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cColonKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Keyword cZoomKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Assignment cZoomAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cZoomINTTerminalRuleCall_4_0 = (RuleCall)cZoomAssignment_4.eContents().get(0);
		
		//ModelProperties:
		//	('properties' ':' | 'properties:') ('viewport' ':' | 'viewport:') point=Point ('zoom' ':' | 'zoom:') zoom=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//('properties' ':' | 'properties:') ('viewport' ':' | 'viewport:') point=Point ('zoom' ':' | 'zoom:') zoom=INT
		public Group getGroup() { return cGroup; }
		
		//('properties' ':' | 'properties:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'properties' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'properties'
		public Keyword getPropertiesKeyword_0_0_0() { return cPropertiesKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'properties:'
		public Keyword getPropertiesKeyword_0_1() { return cPropertiesKeyword_0_1; }
		
		//('viewport' ':' | 'viewport:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'viewport' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'viewport'
		public Keyword getViewportKeyword_1_0_0() { return cViewportKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'viewport:'
		public Keyword getViewportKeyword_1_1() { return cViewportKeyword_1_1; }
		
		//point=Point
		public Assignment getPointAssignment_2() { return cPointAssignment_2; }
		
		//Point
		public RuleCall getPointPointParserRuleCall_2_0() { return cPointPointParserRuleCall_2_0; }
		
		//('zoom' ':' | 'zoom:')
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'zoom' ':'
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'zoom'
		public Keyword getZoomKeyword_3_0_0() { return cZoomKeyword_3_0_0; }
		
		//':'
		public Keyword getColonKeyword_3_0_1() { return cColonKeyword_3_0_1; }
		
		//'zoom:'
		public Keyword getZoomKeyword_3_1() { return cZoomKeyword_3_1; }
		
		//zoom=INT
		public Assignment getZoomAssignment_4() { return cZoomAssignment_4; }
		
		//INT
		public RuleCall getZoomINTTerminalRuleCall_4_0() { return cZoomINTTerminalRuleCall_4_0; }
	}
	public class GraphicalElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.GraphicalElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cShapesParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cConnectorsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//GraphicalElement:
		//	Shapes | Connectors;
		@Override public ParserRule getRule() { return rule; }
		
		//Shapes | Connectors
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Shapes
		public RuleCall getShapesParserRuleCall_0() { return cShapesParserRuleCall_0; }
		
		//Connectors
		public RuleCall getConnectorsParserRuleCall_1() { return cConnectorsParserRuleCall_1; }
	}
	public class ShapesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Shapes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cShapesAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cShapesKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cShapesKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cShapesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cShapesShapeParserRuleCall_2_0 = (RuleCall)cShapesAssignment_2.eContents().get(0);
		
		//Shapes:
		//	{Shapes} ('shapes' ':' | 'shapes:') shapes+=Shape*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Shapes} ('shapes' ':' | 'shapes:') shapes+=Shape*
		public Group getGroup() { return cGroup; }
		
		//{Shapes}
		public Action getShapesAction_0() { return cShapesAction_0; }
		
		//('shapes' ':' | 'shapes:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'shapes' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'shapes'
		public Keyword getShapesKeyword_1_0_0() { return cShapesKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'shapes:'
		public Keyword getShapesKeyword_1_1() { return cShapesKeyword_1_1; }
		
		//shapes+=Shape*
		public Assignment getShapesAssignment_2() { return cShapesAssignment_2; }
		
		//Shape
		public RuleCall getShapesShapeParserRuleCall_2_0() { return cShapesShapeParserRuleCall_2_0; }
	}
	public class ShapeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Shape");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cShapeAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cShapeKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cShapeKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Assignment cContainerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cContainerContainerParserRuleCall_3_0 = (RuleCall)cContainerAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cAlternatives_4.eContents().get(0);
		private final Keyword cRenderKeyword_4_0_0 = (Keyword)cGroup_4_0.eContents().get(0);
		private final Keyword cColonKeyword_4_0_1 = (Keyword)cGroup_4_0.eContents().get(1);
		private final Keyword cRenderKeyword_4_1 = (Keyword)cAlternatives_4.eContents().get(1);
		private final Assignment cRepresentsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRepresentsSTRINGTerminalRuleCall_5_0 = (RuleCall)cRepresentsAssignment_5.eContents().get(0);
		private final Assignment cRectAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRectRectangleParserRuleCall_6_0 = (RuleCall)cRectAssignment_6.eContents().get(0);
		private final Assignment cTextAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTextFloatingTextParserRuleCall_7_0 = (RuleCall)cTextAssignment_7.eContents().get(0);
		
		//Shape:
		//	{Shape} ('shape' ':' | 'shape:') name=ID
		//	container=Container? ('render' ':' | 'render:') represents=STRING
		//	rect=Rectangle text=FloatingText?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Shape} ('shape' ':' | 'shape:') name=ID container=Container? ('render' ':' | 'render:') represents=STRING
		//rect=Rectangle text=FloatingText?
		public Group getGroup() { return cGroup; }
		
		//{Shape}
		public Action getShapeAction_0() { return cShapeAction_0; }
		
		//('shape' ':' | 'shape:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'shape' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'shape'
		public Keyword getShapeKeyword_1_0_0() { return cShapeKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'shape:'
		public Keyword getShapeKeyword_1_1() { return cShapeKeyword_1_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//container=Container?
		public Assignment getContainerAssignment_3() { return cContainerAssignment_3; }
		
		//Container
		public RuleCall getContainerContainerParserRuleCall_3_0() { return cContainerContainerParserRuleCall_3_0; }
		
		//('render' ':' | 'render:')
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//'render' ':'
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//'render'
		public Keyword getRenderKeyword_4_0_0() { return cRenderKeyword_4_0_0; }
		
		//':'
		public Keyword getColonKeyword_4_0_1() { return cColonKeyword_4_0_1; }
		
		//'render:'
		public Keyword getRenderKeyword_4_1() { return cRenderKeyword_4_1; }
		
		//represents=STRING
		public Assignment getRepresentsAssignment_5() { return cRepresentsAssignment_5; }
		
		//STRING
		public RuleCall getRepresentsSTRINGTerminalRuleCall_5_0() { return cRepresentsSTRINGTerminalRuleCall_5_0; }
		
		//rect=Rectangle
		public Assignment getRectAssignment_6() { return cRectAssignment_6; }
		
		//Rectangle
		public RuleCall getRectRectangleParserRuleCall_6_0() { return cRectRectangleParserRuleCall_6_0; }
		
		//text=FloatingText?
		public Assignment getTextAssignment_7() { return cTextAssignment_7; }
		
		//FloatingText
		public RuleCall getTextFloatingTextParserRuleCall_7_0() { return cTextFloatingTextParserRuleCall_7_0; }
	}
	public class ContainerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Container");
		private final Keyword cContainerKeyword = (Keyword)rule.eContents().get(1);
		
		//Container:
		//	'container';
		@Override public ParserRule getRule() { return rule; }
		
		//'container'
		public Keyword getContainerKeyword() { return cContainerKeyword; }
	}
	public class FloatingTextsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.FloatingTexts");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFloatingTextsAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cTextsKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cTextsKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cTextsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextsFloatingTextParserRuleCall_2_0 = (RuleCall)cTextsAssignment_2.eContents().get(0);
		
		//FloatingTexts:
		//	{FloatingTexts} ('texts' ':' | 'texts:') texts+=FloatingText*;
		@Override public ParserRule getRule() { return rule; }
		
		//{FloatingTexts} ('texts' ':' | 'texts:') texts+=FloatingText*
		public Group getGroup() { return cGroup; }
		
		//{FloatingTexts}
		public Action getFloatingTextsAction_0() { return cFloatingTextsAction_0; }
		
		//('texts' ':' | 'texts:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'texts' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'texts'
		public Keyword getTextsKeyword_1_0_0() { return cTextsKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'texts:'
		public Keyword getTextsKeyword_1_1() { return cTextsKeyword_1_1; }
		
		//texts+=FloatingText*
		public Assignment getTextsAssignment_2() { return cTextsAssignment_2; }
		
		//FloatingText
		public RuleCall getTextsFloatingTextParserRuleCall_2_0() { return cTextsFloatingTextParserRuleCall_2_0; }
	}
	public class FloatingTextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.FloatingText");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFloatingTextAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cTextKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cTextKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cRectAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRectRectangleParserRuleCall_2_0 = (RuleCall)cRectAssignment_2.eContents().get(0);
		private final Assignment cEndAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEndEnumEndParserRuleCall_3_0 = (RuleCall)cEndAssignment_3.eContents().get(0);
		
		//FloatingText:
		//	{FloatingText} ('text' ':' | 'text:') rect=Rectangle
		//	end=EnumEnd;
		@Override public ParserRule getRule() { return rule; }
		
		//{FloatingText} ('text' ':' | 'text:') rect=Rectangle end=EnumEnd
		public Group getGroup() { return cGroup; }
		
		//{FloatingText}
		public Action getFloatingTextAction_0() { return cFloatingTextAction_0; }
		
		//('text' ':' | 'text:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'text' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'text'
		public Keyword getTextKeyword_1_0_0() { return cTextKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'text:'
		public Keyword getTextKeyword_1_1() { return cTextKeyword_1_1; }
		
		//rect=Rectangle
		public Assignment getRectAssignment_2() { return cRectAssignment_2; }
		
		//Rectangle
		public RuleCall getRectRectangleParserRuleCall_2_0() { return cRectRectangleParserRuleCall_2_0; }
		
		//end=EnumEnd
		public Assignment getEndAssignment_3() { return cEndAssignment_3; }
		
		//EnumEnd
		public RuleCall getEndEnumEndParserRuleCall_3_0() { return cEndEnumEndParserRuleCall_3_0; }
	}
	public class EnumEndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.EnumEnd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cWhereKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cWhereKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cWhereAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cWhereAlternatives_1_0 = (Alternatives)cWhereAssignment_1.eContents().get(0);
		private final Keyword cWhereStartKeyword_1_0_0 = (Keyword)cWhereAlternatives_1_0.eContents().get(0);
		private final Keyword cWhereEndKeyword_1_0_1 = (Keyword)cWhereAlternatives_1_0.eContents().get(1);
		private final Keyword cWhereMiddleKeyword_1_0_2 = (Keyword)cWhereAlternatives_1_0.eContents().get(2);
		private final Keyword cWhereEnd_fixedKeyword_1_0_3 = (Keyword)cWhereAlternatives_1_0.eContents().get(3);
		private final Keyword cWhereStart_fixedKeyword_1_0_4 = (Keyword)cWhereAlternatives_1_0.eContents().get(4);
		private final Keyword cWhereNoneKeyword_1_0_5 = (Keyword)cWhereAlternatives_1_0.eContents().get(5);
		private final Keyword cWhereFloatingKeyword_1_0_6 = (Keyword)cWhereAlternatives_1_0.eContents().get(6);
		private final Keyword cWhereAdditionalKeyword_1_0_7 = (Keyword)cWhereAlternatives_1_0.eContents().get(7);
		
		//EnumEnd:
		//	('where' ':' | 'where:') where=('start' | 'end' | 'middle' | 'end_fixed' | 'start_fixed' | 'none' | 'floating' |
		//	'additional');
		@Override public ParserRule getRule() { return rule; }
		
		//('where' ':' | 'where:') where=('start' | 'end' | 'middle' | 'end_fixed' | 'start_fixed' | 'none' | 'floating' |
		//'additional')
		public Group getGroup() { return cGroup; }
		
		//('where' ':' | 'where:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'where' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'where'
		public Keyword getWhereKeyword_0_0_0() { return cWhereKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'where:'
		public Keyword getWhereKeyword_0_1() { return cWhereKeyword_0_1; }
		
		//where=('start' | 'end' | 'middle' | 'end_fixed' | 'start_fixed' | 'none' | 'floating' | 'additional')
		public Assignment getWhereAssignment_1() { return cWhereAssignment_1; }
		
		//('start' | 'end' | 'middle' | 'end_fixed' | 'start_fixed' | 'none' | 'floating' | 'additional')
		public Alternatives getWhereAlternatives_1_0() { return cWhereAlternatives_1_0; }
		
		//'start'
		public Keyword getWhereStartKeyword_1_0_0() { return cWhereStartKeyword_1_0_0; }
		
		//'end'
		public Keyword getWhereEndKeyword_1_0_1() { return cWhereEndKeyword_1_0_1; }
		
		//'middle'
		public Keyword getWhereMiddleKeyword_1_0_2() { return cWhereMiddleKeyword_1_0_2; }
		
		//'end_fixed'
		public Keyword getWhereEnd_fixedKeyword_1_0_3() { return cWhereEnd_fixedKeyword_1_0_3; }
		
		//'start_fixed'
		public Keyword getWhereStart_fixedKeyword_1_0_4() { return cWhereStart_fixedKeyword_1_0_4; }
		
		//'none'
		public Keyword getWhereNoneKeyword_1_0_5() { return cWhereNoneKeyword_1_0_5; }
		
		//'floating'
		public Keyword getWhereFloatingKeyword_1_0_6() { return cWhereFloatingKeyword_1_0_6; }
		
		//'additional'
		public Keyword getWhereAdditionalKeyword_1_0_7() { return cWhereAdditionalKeyword_1_0_7; }
	}
	public class ConnectorsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Connectors");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConnectorsAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cConnectorsKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cConnectorsKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cConnectorsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConnectorsConnectorParserRuleCall_2_0 = (RuleCall)cConnectorsAssignment_2.eContents().get(0);
		
		//Connectors:
		//	{Connectors} ('connectors' ':' | 'connectors:') connectors+=Connector*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Connectors} ('connectors' ':' | 'connectors:') connectors+=Connector*
		public Group getGroup() { return cGroup; }
		
		//{Connectors}
		public Action getConnectorsAction_0() { return cConnectorsAction_0; }
		
		//('connectors' ':' | 'connectors:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'connectors' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'connectors'
		public Keyword getConnectorsKeyword_1_0_0() { return cConnectorsKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'connectors:'
		public Keyword getConnectorsKeyword_1_1() { return cConnectorsKeyword_1_1; }
		
		//connectors+=Connector*
		public Assignment getConnectorsAssignment_2() { return cConnectorsAssignment_2; }
		
		//Connector
		public RuleCall getConnectorsConnectorParserRuleCall_2_0() { return cConnectorsConnectorParserRuleCall_2_0; }
	}
	public class ConnectorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Connector");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cConnectorKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cConnectorKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cRenderKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Keyword cColonKeyword_2_0_1 = (Keyword)cGroup_2_0.eContents().get(1);
		private final Keyword cRenderKeyword_2_1 = (Keyword)cAlternatives_2.eContents().get(1);
		private final Assignment cRepresentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRepresentsSTRINGTerminalRuleCall_3_0 = (RuleCall)cRepresentsAssignment_3.eContents().get(0);
		private final Assignment cPolylineAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPolylinePolylineParserRuleCall_4_0 = (RuleCall)cPolylineAssignment_4.eContents().get(0);
		private final Assignment cAnchorsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAnchorsAnchorsParserRuleCall_5_0 = (RuleCall)cAnchorsAssignment_5.eContents().get(0);
		private final Assignment cTextsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTextsFloatingTextsParserRuleCall_6_0 = (RuleCall)cTextsAssignment_6.eContents().get(0);
		
		//Connector:
		//	('connector' ':' | 'connector:') name=ID ('render' ':' | 'render:') represents=STRING
		//	polyline=Polyline
		//	anchors=Anchors? texts=FloatingTexts;
		@Override public ParserRule getRule() { return rule; }
		
		//('connector' ':' | 'connector:') name=ID ('render' ':' | 'render:') represents=STRING polyline=Polyline anchors=Anchors?
		//texts=FloatingTexts
		public Group getGroup() { return cGroup; }
		
		//('connector' ':' | 'connector:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'connector' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'connector'
		public Keyword getConnectorKeyword_0_0_0() { return cConnectorKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'connector:'
		public Keyword getConnectorKeyword_0_1() { return cConnectorKeyword_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//('render' ':' | 'render:')
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//'render' ':'
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//'render'
		public Keyword getRenderKeyword_2_0_0() { return cRenderKeyword_2_0_0; }
		
		//':'
		public Keyword getColonKeyword_2_0_1() { return cColonKeyword_2_0_1; }
		
		//'render:'
		public Keyword getRenderKeyword_2_1() { return cRenderKeyword_2_1; }
		
		//represents=STRING
		public Assignment getRepresentsAssignment_3() { return cRepresentsAssignment_3; }
		
		//STRING
		public RuleCall getRepresentsSTRINGTerminalRuleCall_3_0() { return cRepresentsSTRINGTerminalRuleCall_3_0; }
		
		//polyline=Polyline
		public Assignment getPolylineAssignment_4() { return cPolylineAssignment_4; }
		
		//Polyline
		public RuleCall getPolylinePolylineParserRuleCall_4_0() { return cPolylinePolylineParserRuleCall_4_0; }
		
		//anchors=Anchors?
		public Assignment getAnchorsAssignment_5() { return cAnchorsAssignment_5; }
		
		//Anchors
		public RuleCall getAnchorsAnchorsParserRuleCall_5_0() { return cAnchorsAnchorsParserRuleCall_5_0; }
		
		//texts=FloatingTexts
		public Assignment getTextsAssignment_6() { return cTextsAssignment_6; }
		
		//FloatingTexts
		public RuleCall getTextsFloatingTextsParserRuleCall_6_0() { return cTextsFloatingTextsParserRuleCall_6_0; }
	}
	public class AnchorsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Anchors");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cAnchorsKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cAnchorsKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cStartAnchorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cStartAnchorStartAnchorParserRuleCall_1_0 = (RuleCall)cStartAnchorAssignment_1.eContents().get(0);
		private final Assignment cEndAnchorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEndAnchorEndAnchorParserRuleCall_2_0 = (RuleCall)cEndAnchorAssignment_2.eContents().get(0);
		
		//Anchors:
		//	('anchors' ':' | 'anchors:') startAnchor=StartAnchor endAnchor=EndAnchor;
		@Override public ParserRule getRule() { return rule; }
		
		//('anchors' ':' | 'anchors:') startAnchor=StartAnchor endAnchor=EndAnchor
		public Group getGroup() { return cGroup; }
		
		//('anchors' ':' | 'anchors:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'anchors' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'anchors'
		public Keyword getAnchorsKeyword_0_0_0() { return cAnchorsKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'anchors:'
		public Keyword getAnchorsKeyword_0_1() { return cAnchorsKeyword_0_1; }
		
		//startAnchor=StartAnchor
		public Assignment getStartAnchorAssignment_1() { return cStartAnchorAssignment_1; }
		
		//StartAnchor
		public RuleCall getStartAnchorStartAnchorParserRuleCall_1_0() { return cStartAnchorStartAnchorParserRuleCall_1_0; }
		
		//endAnchor=EndAnchor
		public Assignment getEndAnchorAssignment_2() { return cEndAnchorAssignment_2; }
		
		//EndAnchor
		public RuleCall getEndAnchorEndAnchorParserRuleCall_2_0() { return cEndAnchorEndAnchorParserRuleCall_2_0; }
	}
	public class StartAnchorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.StartAnchor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cStartKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cStartKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cPointAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPointPointDefinitionParserRuleCall_1_0 = (RuleCall)cPointAssignment_1.eContents().get(0);
		private final Assignment cAnchorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAnchorAnchorParserRuleCall_2_0 = (RuleCall)cAnchorAssignment_2.eContents().get(0);
		
		//StartAnchor:
		//	('start' ':' | 'start:') point=PointDefinition anchor=Anchor?;
		@Override public ParserRule getRule() { return rule; }
		
		//('start' ':' | 'start:') point=PointDefinition anchor=Anchor?
		public Group getGroup() { return cGroup; }
		
		//('start' ':' | 'start:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'start' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'start'
		public Keyword getStartKeyword_0_0_0() { return cStartKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'start:'
		public Keyword getStartKeyword_0_1() { return cStartKeyword_0_1; }
		
		//point=PointDefinition
		public Assignment getPointAssignment_1() { return cPointAssignment_1; }
		
		//PointDefinition
		public RuleCall getPointPointDefinitionParserRuleCall_1_0() { return cPointPointDefinitionParserRuleCall_1_0; }
		
		//anchor=Anchor?
		public Assignment getAnchorAssignment_2() { return cAnchorAssignment_2; }
		
		//Anchor
		public RuleCall getAnchorAnchorParserRuleCall_2_0() { return cAnchorAnchorParserRuleCall_2_0; }
	}
	public class EndAnchorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.EndAnchor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cEndKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cEndKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cPointAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPointPointDefinitionParserRuleCall_1_0 = (RuleCall)cPointAssignment_1.eContents().get(0);
		private final Assignment cAnchorAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAnchorAnchorParserRuleCall_2_0 = (RuleCall)cAnchorAssignment_2.eContents().get(0);
		
		//EndAnchor:
		//	('end' ':' | 'end:') point=PointDefinition anchor=Anchor?;
		@Override public ParserRule getRule() { return rule; }
		
		//('end' ':' | 'end:') point=PointDefinition anchor=Anchor?
		public Group getGroup() { return cGroup; }
		
		//('end' ':' | 'end:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'end' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'end'
		public Keyword getEndKeyword_0_0_0() { return cEndKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'end:'
		public Keyword getEndKeyword_0_1() { return cEndKeyword_0_1; }
		
		//point=PointDefinition
		public Assignment getPointAssignment_1() { return cPointAssignment_1; }
		
		//PointDefinition
		public RuleCall getPointPointDefinitionParserRuleCall_1_0() { return cPointPointDefinitionParserRuleCall_1_0; }
		
		//anchor=Anchor?
		public Assignment getAnchorAssignment_2() { return cAnchorAssignment_2; }
		
		//Anchor
		public RuleCall getAnchorAnchorParserRuleCall_2_0() { return cAnchorAnchorParserRuleCall_2_0; }
	}
	public class AnchorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Anchor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cShapeAnchorElementParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cConnectorAnchorElementParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Anchor:
		//	ShapeAnchorElement | ConnectorAnchorElement;
		@Override public ParserRule getRule() { return rule; }
		
		//ShapeAnchorElement | ConnectorAnchorElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ShapeAnchorElement
		public RuleCall getShapeAnchorElementParserRuleCall_0() { return cShapeAnchorElementParserRuleCall_0; }
		
		//ConnectorAnchorElement
		public RuleCall getConnectorAnchorElementParserRuleCall_1() { return cConnectorAnchorElementParserRuleCall_1; }
	}
	public class ShapeAnchorElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.ShapeAnchorElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cShapeKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cShapeKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cElementShapeCrossReference_1_0 = (CrossReference)cElementAssignment_1.eContents().get(0);
		private final RuleCall cElementShapeIDTerminalRuleCall_1_0_1 = (RuleCall)cElementShapeCrossReference_1_0.eContents().get(1);
		
		//ShapeAnchorElement:
		//	('shape' ':' | 'shape:') element=[Shape];
		@Override public ParserRule getRule() { return rule; }
		
		//('shape' ':' | 'shape:') element=[Shape]
		public Group getGroup() { return cGroup; }
		
		//('shape' ':' | 'shape:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'shape' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'shape'
		public Keyword getShapeKeyword_0_0_0() { return cShapeKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'shape:'
		public Keyword getShapeKeyword_0_1() { return cShapeKeyword_0_1; }
		
		//element=[Shape]
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//[Shape]
		public CrossReference getElementShapeCrossReference_1_0() { return cElementShapeCrossReference_1_0; }
		
		//ID
		public RuleCall getElementShapeIDTerminalRuleCall_1_0_1() { return cElementShapeIDTerminalRuleCall_1_0_1; }
	}
	public class ConnectorAnchorElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.ConnectorAnchorElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cConnectorKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cConnectorKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cElementConnectorCrossReference_1_0 = (CrossReference)cElementAssignment_1.eContents().get(0);
		private final RuleCall cElementConnectorIDTerminalRuleCall_1_0_1 = (RuleCall)cElementConnectorCrossReference_1_0.eContents().get(1);
		
		//ConnectorAnchorElement:
		//	('connector' ':' | 'connector:') element=[Connector];
		@Override public ParserRule getRule() { return rule; }
		
		//('connector' ':' | 'connector:') element=[Connector]
		public Group getGroup() { return cGroup; }
		
		//('connector' ':' | 'connector:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'connector' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'connector'
		public Keyword getConnectorKeyword_0_0_0() { return cConnectorKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'connector:'
		public Keyword getConnectorKeyword_0_1() { return cConnectorKeyword_0_1; }
		
		//element=[Connector]
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//[Connector]
		public CrossReference getElementConnectorCrossReference_1_0() { return cElementConnectorCrossReference_1_0; }
		
		//ID
		public RuleCall getElementConnectorIDTerminalRuleCall_1_0_1() { return cElementConnectorIDTerminalRuleCall_1_0_1; }
	}
	public class PolylineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Polyline");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPolylineAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cPolylineKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cPolylineKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cSegmentsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSegmentsSegmentParserRuleCall_2_0 = (RuleCall)cSegmentsAssignment_2.eContents().get(0);
		
		//Polyline:
		//	{Polyline} ('polyline' ':' | 'polyline:') segments+=Segment*;
		@Override public ParserRule getRule() { return rule; }
		
		//{Polyline} ('polyline' ':' | 'polyline:') segments+=Segment*
		public Group getGroup() { return cGroup; }
		
		//{Polyline}
		public Action getPolylineAction_0() { return cPolylineAction_0; }
		
		//('polyline' ':' | 'polyline:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'polyline' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'polyline'
		public Keyword getPolylineKeyword_1_0_0() { return cPolylineKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'polyline:'
		public Keyword getPolylineKeyword_1_1() { return cPolylineKeyword_1_1; }
		
		//segments+=Segment*
		public Assignment getSegmentsAssignment_2() { return cSegmentsAssignment_2; }
		
		//Segment
		public RuleCall getSegmentsSegmentParserRuleCall_2_0() { return cSegmentsSegmentParserRuleCall_2_0; }
	}
	public class SegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Segment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cSegmentKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cSegmentKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cStartKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Keyword cStartKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cStartPointAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStartPointPointParserRuleCall_2_0 = (RuleCall)cStartPointAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cEndKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Keyword cColonKeyword_3_0_1 = (Keyword)cGroup_3_0.eContents().get(1);
		private final Keyword cEndKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		private final Assignment cEndPointAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEndPointPointParserRuleCall_4_0 = (RuleCall)cEndPointAssignment_4.eContents().get(0);
		
		//Segment:
		//	('segment' ':' | 'segment:') ('start' ':' | 'start:') startPoint=Point ('end' ':' | 'end:') endPoint=Point;
		@Override public ParserRule getRule() { return rule; }
		
		//('segment' ':' | 'segment:') ('start' ':' | 'start:') startPoint=Point ('end' ':' | 'end:') endPoint=Point
		public Group getGroup() { return cGroup; }
		
		//('segment' ':' | 'segment:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'segment' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'segment'
		public Keyword getSegmentKeyword_0_0_0() { return cSegmentKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'segment:'
		public Keyword getSegmentKeyword_0_1() { return cSegmentKeyword_0_1; }
		
		//('start' ':' | 'start:')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'start' ':'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'start'
		public Keyword getStartKeyword_1_0_0() { return cStartKeyword_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_0_1() { return cColonKeyword_1_0_1; }
		
		//'start:'
		public Keyword getStartKeyword_1_1() { return cStartKeyword_1_1; }
		
		//startPoint=Point
		public Assignment getStartPointAssignment_2() { return cStartPointAssignment_2; }
		
		//Point
		public RuleCall getStartPointPointParserRuleCall_2_0() { return cStartPointPointParserRuleCall_2_0; }
		
		//('end' ':' | 'end:')
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'end' ':'
		public Group getGroup_3_0() { return cGroup_3_0; }
		
		//'end'
		public Keyword getEndKeyword_3_0_0() { return cEndKeyword_3_0_0; }
		
		//':'
		public Keyword getColonKeyword_3_0_1() { return cColonKeyword_3_0_1; }
		
		//'end:'
		public Keyword getEndKeyword_3_1() { return cEndKeyword_3_1; }
		
		//endPoint=Point
		public Assignment getEndPointAssignment_4() { return cEndPointAssignment_4; }
		
		//Point
		public RuleCall getEndPointPointParserRuleCall_4_0() { return cEndPointPointParserRuleCall_4_0; }
	}
	public class PointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Point");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cXKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXINTTerminalRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Keyword cYKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cYAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cYINTTerminalRuleCall_3_0 = (RuleCall)cYAssignment_3.eContents().get(0);
		
		//Point:
		//	'x' x=INT 'y' y=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'x' x=INT 'y' y=INT
		public Group getGroup() { return cGroup; }
		
		//'x'
		public Keyword getXKeyword_0() { return cXKeyword_0; }
		
		//x=INT
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_1_0() { return cXINTTerminalRuleCall_1_0; }
		
		//'y'
		public Keyword getYKeyword_2() { return cYKeyword_2; }
		
		//y=INT
		public Assignment getYAssignment_3() { return cYAssignment_3; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_3_0() { return cYINTTerminalRuleCall_3_0; }
	}
	public class PointDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.PointDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cPointKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cPointKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cXKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXINTTerminalRuleCall_2_0 = (RuleCall)cXAssignment_2.eContents().get(0);
		private final Keyword cYKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYINTTerminalRuleCall_4_0 = (RuleCall)cYAssignment_4.eContents().get(0);
		
		//PointDefinition:
		//	('point' ':' | 'point:')
		//	'x' x=INT 'y' y=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//('point' ':' | 'point:') 'x' x=INT 'y' y=INT
		public Group getGroup() { return cGroup; }
		
		//('point' ':' | 'point:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'point' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'point'
		public Keyword getPointKeyword_0_0_0() { return cPointKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'point:'
		public Keyword getPointKeyword_0_1() { return cPointKeyword_0_1; }
		
		//'x'
		public Keyword getXKeyword_1() { return cXKeyword_1; }
		
		//x=INT
		public Assignment getXAssignment_2() { return cXAssignment_2; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_2_0() { return cXINTTerminalRuleCall_2_0; }
		
		//'y'
		public Keyword getYKeyword_3() { return cYKeyword_3; }
		
		//y=INT
		public Assignment getYAssignment_4() { return cYAssignment_4; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_4_0() { return cYINTTerminalRuleCall_4_0; }
	}
	public class RectangleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtuml.canvas.language.Canvas.Rectangle");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cRectangleKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Keyword cColonKeyword_0_0_1 = (Keyword)cGroup_0_0.eContents().get(1);
		private final Keyword cRectangleKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cXKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXINTTerminalRuleCall_2_0 = (RuleCall)cXAssignment_2.eContents().get(0);
		private final Keyword cYKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYINTTerminalRuleCall_4_0 = (RuleCall)cYAssignment_4.eContents().get(0);
		private final Keyword cWidthKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cWAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cWINTTerminalRuleCall_6_0 = (RuleCall)cWAssignment_6.eContents().get(0);
		private final Keyword cHeightKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cHAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cHINTTerminalRuleCall_8_0 = (RuleCall)cHAssignment_8.eContents().get(0);
		
		//Rectangle:
		//	('rectangle' ':' | 'rectangle:')
		//	'x' x=INT
		//	'y' y=INT
		//	'width' w=INT
		//	'height' h=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//('rectangle' ':' | 'rectangle:') 'x' x=INT 'y' y=INT 'width' w=INT 'height' h=INT
		public Group getGroup() { return cGroup; }
		
		//('rectangle' ':' | 'rectangle:')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'rectangle' ':'
		public Group getGroup_0_0() { return cGroup_0_0; }
		
		//'rectangle'
		public Keyword getRectangleKeyword_0_0_0() { return cRectangleKeyword_0_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_0_1() { return cColonKeyword_0_0_1; }
		
		//'rectangle:'
		public Keyword getRectangleKeyword_0_1() { return cRectangleKeyword_0_1; }
		
		//'x'
		public Keyword getXKeyword_1() { return cXKeyword_1; }
		
		//x=INT
		public Assignment getXAssignment_2() { return cXAssignment_2; }
		
		//INT
		public RuleCall getXINTTerminalRuleCall_2_0() { return cXINTTerminalRuleCall_2_0; }
		
		//'y'
		public Keyword getYKeyword_3() { return cYKeyword_3; }
		
		//y=INT
		public Assignment getYAssignment_4() { return cYAssignment_4; }
		
		//INT
		public RuleCall getYINTTerminalRuleCall_4_0() { return cYINTTerminalRuleCall_4_0; }
		
		//'width'
		public Keyword getWidthKeyword_5() { return cWidthKeyword_5; }
		
		//w=INT
		public Assignment getWAssignment_6() { return cWAssignment_6; }
		
		//INT
		public RuleCall getWINTTerminalRuleCall_6_0() { return cWINTTerminalRuleCall_6_0; }
		
		//'height'
		public Keyword getHeightKeyword_7() { return cHeightKeyword_7; }
		
		//h=INT
		public Assignment getHAssignment_8() { return cHAssignment_8; }
		
		//INT
		public RuleCall getHINTTerminalRuleCall_8_0() { return cHINTTerminalRuleCall_8_0; }
	}
	
	
	private final ModelElements pModel;
	private final ModelRenderElements pModelRender;
	private final ModelPropertiesElements pModelProperties;
	private final GraphicalElementElements pGraphicalElement;
	private final ShapesElements pShapes;
	private final ShapeElements pShape;
	private final ContainerElements pContainer;
	private final FloatingTextsElements pFloatingTexts;
	private final FloatingTextElements pFloatingText;
	private final EnumEndElements pEnumEnd;
	private final ConnectorsElements pConnectors;
	private final ConnectorElements pConnector;
	private final AnchorsElements pAnchors;
	private final StartAnchorElements pStartAnchor;
	private final EndAnchorElements pEndAnchor;
	private final AnchorElements pAnchor;
	private final ShapeAnchorElementElements pShapeAnchorElement;
	private final ConnectorAnchorElementElements pConnectorAnchorElement;
	private final PolylineElements pPolyline;
	private final SegmentElements pSegment;
	private final PointElements pPoint;
	private final PointDefinitionElements pPointDefinition;
	private final RectangleElements pRectangle;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CanvasGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pModelRender = new ModelRenderElements();
		this.pModelProperties = new ModelPropertiesElements();
		this.pGraphicalElement = new GraphicalElementElements();
		this.pShapes = new ShapesElements();
		this.pShape = new ShapeElements();
		this.pContainer = new ContainerElements();
		this.pFloatingTexts = new FloatingTextsElements();
		this.pFloatingText = new FloatingTextElements();
		this.pEnumEnd = new EnumEndElements();
		this.pConnectors = new ConnectorsElements();
		this.pConnector = new ConnectorElements();
		this.pAnchors = new AnchorsElements();
		this.pStartAnchor = new StartAnchorElements();
		this.pEndAnchor = new EndAnchorElements();
		this.pAnchor = new AnchorElements();
		this.pShapeAnchorElement = new ShapeAnchorElementElements();
		this.pConnectorAnchorElement = new ConnectorAnchorElementElements();
		this.pPolyline = new PolylineElements();
		this.pSegment = new SegmentElements();
		this.pPoint = new PointElements();
		this.pPointDefinition = new PointDefinitionElements();
		this.pRectangle = new RectangleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtuml.canvas.language.Canvas".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	render=ModelRender
	//	properties=ModelProperties?
	//	elements+=GraphicalElement*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//ModelRender:
	//	('render' ':' | 'render:') importURI=STRING;
	public ModelRenderElements getModelRenderAccess() {
		return pModelRender;
	}
	
	public ParserRule getModelRenderRule() {
		return getModelRenderAccess().getRule();
	}
	
	//ModelProperties:
	//	('properties' ':' | 'properties:') ('viewport' ':' | 'viewport:') point=Point ('zoom' ':' | 'zoom:') zoom=INT;
	public ModelPropertiesElements getModelPropertiesAccess() {
		return pModelProperties;
	}
	
	public ParserRule getModelPropertiesRule() {
		return getModelPropertiesAccess().getRule();
	}
	
	//GraphicalElement:
	//	Shapes | Connectors;
	public GraphicalElementElements getGraphicalElementAccess() {
		return pGraphicalElement;
	}
	
	public ParserRule getGraphicalElementRule() {
		return getGraphicalElementAccess().getRule();
	}
	
	//Shapes:
	//	{Shapes} ('shapes' ':' | 'shapes:') shapes+=Shape*;
	public ShapesElements getShapesAccess() {
		return pShapes;
	}
	
	public ParserRule getShapesRule() {
		return getShapesAccess().getRule();
	}
	
	//Shape:
	//	{Shape} ('shape' ':' | 'shape:') name=ID
	//	container=Container? ('render' ':' | 'render:') represents=STRING
	//	rect=Rectangle text=FloatingText?;
	public ShapeElements getShapeAccess() {
		return pShape;
	}
	
	public ParserRule getShapeRule() {
		return getShapeAccess().getRule();
	}
	
	//Container:
	//	'container';
	public ContainerElements getContainerAccess() {
		return pContainer;
	}
	
	public ParserRule getContainerRule() {
		return getContainerAccess().getRule();
	}
	
	//FloatingTexts:
	//	{FloatingTexts} ('texts' ':' | 'texts:') texts+=FloatingText*;
	public FloatingTextsElements getFloatingTextsAccess() {
		return pFloatingTexts;
	}
	
	public ParserRule getFloatingTextsRule() {
		return getFloatingTextsAccess().getRule();
	}
	
	//FloatingText:
	//	{FloatingText} ('text' ':' | 'text:') rect=Rectangle
	//	end=EnumEnd;
	public FloatingTextElements getFloatingTextAccess() {
		return pFloatingText;
	}
	
	public ParserRule getFloatingTextRule() {
		return getFloatingTextAccess().getRule();
	}
	
	//EnumEnd:
	//	('where' ':' | 'where:') where=('start' | 'end' | 'middle' | 'end_fixed' | 'start_fixed' | 'none' | 'floating' |
	//	'additional');
	public EnumEndElements getEnumEndAccess() {
		return pEnumEnd;
	}
	
	public ParserRule getEnumEndRule() {
		return getEnumEndAccess().getRule();
	}
	
	//Connectors:
	//	{Connectors} ('connectors' ':' | 'connectors:') connectors+=Connector*;
	public ConnectorsElements getConnectorsAccess() {
		return pConnectors;
	}
	
	public ParserRule getConnectorsRule() {
		return getConnectorsAccess().getRule();
	}
	
	//Connector:
	//	('connector' ':' | 'connector:') name=ID ('render' ':' | 'render:') represents=STRING
	//	polyline=Polyline
	//	anchors=Anchors? texts=FloatingTexts;
	public ConnectorElements getConnectorAccess() {
		return pConnector;
	}
	
	public ParserRule getConnectorRule() {
		return getConnectorAccess().getRule();
	}
	
	//Anchors:
	//	('anchors' ':' | 'anchors:') startAnchor=StartAnchor endAnchor=EndAnchor;
	public AnchorsElements getAnchorsAccess() {
		return pAnchors;
	}
	
	public ParserRule getAnchorsRule() {
		return getAnchorsAccess().getRule();
	}
	
	//StartAnchor:
	//	('start' ':' | 'start:') point=PointDefinition anchor=Anchor?;
	public StartAnchorElements getStartAnchorAccess() {
		return pStartAnchor;
	}
	
	public ParserRule getStartAnchorRule() {
		return getStartAnchorAccess().getRule();
	}
	
	//EndAnchor:
	//	('end' ':' | 'end:') point=PointDefinition anchor=Anchor?;
	public EndAnchorElements getEndAnchorAccess() {
		return pEndAnchor;
	}
	
	public ParserRule getEndAnchorRule() {
		return getEndAnchorAccess().getRule();
	}
	
	//Anchor:
	//	ShapeAnchorElement | ConnectorAnchorElement;
	public AnchorElements getAnchorAccess() {
		return pAnchor;
	}
	
	public ParserRule getAnchorRule() {
		return getAnchorAccess().getRule();
	}
	
	//ShapeAnchorElement:
	//	('shape' ':' | 'shape:') element=[Shape];
	public ShapeAnchorElementElements getShapeAnchorElementAccess() {
		return pShapeAnchorElement;
	}
	
	public ParserRule getShapeAnchorElementRule() {
		return getShapeAnchorElementAccess().getRule();
	}
	
	//ConnectorAnchorElement:
	//	('connector' ':' | 'connector:') element=[Connector];
	public ConnectorAnchorElementElements getConnectorAnchorElementAccess() {
		return pConnectorAnchorElement;
	}
	
	public ParserRule getConnectorAnchorElementRule() {
		return getConnectorAnchorElementAccess().getRule();
	}
	
	//Polyline:
	//	{Polyline} ('polyline' ':' | 'polyline:') segments+=Segment*;
	public PolylineElements getPolylineAccess() {
		return pPolyline;
	}
	
	public ParserRule getPolylineRule() {
		return getPolylineAccess().getRule();
	}
	
	//Segment:
	//	('segment' ':' | 'segment:') ('start' ':' | 'start:') startPoint=Point ('end' ':' | 'end:') endPoint=Point;
	public SegmentElements getSegmentAccess() {
		return pSegment;
	}
	
	public ParserRule getSegmentRule() {
		return getSegmentAccess().getRule();
	}
	
	//Point:
	//	'x' x=INT 'y' y=INT;
	public PointElements getPointAccess() {
		return pPoint;
	}
	
	public ParserRule getPointRule() {
		return getPointAccess().getRule();
	}
	
	//PointDefinition:
	//	('point' ':' | 'point:')
	//	'x' x=INT 'y' y=INT;
	public PointDefinitionElements getPointDefinitionAccess() {
		return pPointDefinition;
	}
	
	public ParserRule getPointDefinitionRule() {
		return getPointDefinitionAccess().getRule();
	}
	
	//Rectangle:
	//	('rectangle' ':' | 'rectangle:')
	//	'x' x=INT
	//	'y' y=INT
	//	'width' w=INT
	//	'height' h=INT;
	public RectangleElements getRectangleAccess() {
		return pRectangle;
	}
	
	public ParserRule getRectangleRule() {
		return getRectangleAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
